Repository platform-mesh/portal, pull requests merged in 2025-09, with the labels that each got.

#76 feat: add iam onboarding env var (#2)
  backend/package-lock.json
  backend/src/app.module.ts
  frontend/package-lock.json
Labels: enhancement, feature, fix

#83 chore(deps): update @platform-mesh/portal-server-lib to v0.3.16
  backend/package-lock.json
  backend/package.json
Labels: chore, fix

#91 feat: enable getting-started node
  frontend/src/app/services/pm-static-settings-config.service.ts
  frontend/src/main.ts
Labels: feature
